const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Function,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Function: 0},
	{Text: 0},
	{Touch: 0},
	{Text2: 0},
	{tiklanabilme: 0},
	{satir: 0},
	{sutun: 0},
	{kutu: 0},
	{Browser: 0},
	{Button: 0},
	{puanTxt: 0},
	{baslikTxt: 0},
	{bg: 0},
	{Audio: 0},
	{Sine: 0},
	{ipucu: 0},
	{atKafasi: 0},
	{logo: 0},
	{ipucuBtn: 0},
	{varmi: 0},
	{Fade: 0},
	{gameOver: 0},
	{giris: 0},
	{anaSayfaBtn: 0},
	{bilgi: 0},
	{oyunnsloy: 0},
	{oynnsloy: 0},
	{emggcnlr: 0},
	{puan: 0},
	{ipucu2: 0},
	{yenile: 0},
	{oyna: 0},
	{Text3: 0},
	{altin: 0},
	{perde: 0},
	{fark: 0},
	{x: 0},
	{skor: 0},
	{mesafe: 0},
	{n: 0},
	{ky: 0},
	{kx: 0},
	{Parameter0: 0}
];

self.InstanceType = {
	Function: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	kutu: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	puanTxt: class extends self.ITextInstance {},
	baslikTxt: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	ipucu: class extends self.ISpriteInstance {},
	atKafasi: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	ipucuBtn: class extends self.IButtonInstance {},
	varmi: class extends self.ITextInstance {},
	gameOver: class extends self.ITextInstance {},
	giris: class extends self.ISpriteInstance {},
	anaSayfaBtn: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	oyunnsloy: class extends self.ISpriteInstance {},
	oynnsloy: class extends self.ISpriteInstance {},
	emggcnlr: class extends self.ISpriteInstance {},
	puan: class extends self.ISpriteInstance {},
	ipucu2: class extends self.ISpriteInstance {},
	yenile: class extends self.ISpriteInstance {},
	oyna: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	altin: class extends self.ISpriteInstance {},
	perde: class extends self.ITiledBackgroundInstance {}
}